name: hangman
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  sqflite: ^2.4.1
  path: ^1.8.3
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/family/
    - assets/images/cousin/
    - assets/images/flower/
    - assets/images/animal/

  #   - assets/images/family/PRINCE.jpg
  #   - assets/images/family/NAZMUL.jpg
  #   - assets/images/family/NISHAT.jpg
  #   - assets/images/family/JAHANARA.jpg
  #   - assets/images/family/AMIRUL.jpg
  #   - assets/images/family/PRIYANKA.jpg
  #   - assets/images/cousin/SH.jpg
  #   - assets/images/cousin/NOO.jpg
  #   - assets/images/flower/JOBA.jpg
  #   - assets/images/flower/RED.jpg